baseurl = "https://www.kawauso-lab.org"
title = "川獺技研 - kawauso-lab"
theme = "hugo-coder"
languagecode = "ja"
defaultcontentlanguage = "ja"

paginate = 20

# disqusShortname = "yourdiscussshortname"

[markup.highlight]
  style = "github-dark"

[params]
  author = "川獺技研 - kawauso-lab"
  # info = ""
  description = "川獺技研のホームページです。"
  keywords = "blog,developer,personal"
  avatarurl = "/images/avatar.png"
  # gravatar = ""

  favicon_64 = "/images/icon-64.png"
  favicon_180 = "/images/icon-180.png"
  touchicon = "/images/icon-180.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = true

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/marineotter/"

# Menu links
[[menu.main]]
  name = "Home"
  weight = 1
  url  = "./"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
[[menu.main]]
  name = "Blog"
  post = "<i class='fa fa-external-link fa-fw'></i>"
  weight = 5
  url  = "https://kawauso-lab.hatenablog.jp/"
