version: '3'
services:
  devcontainer:
    build: 
      context: .
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
    command: /bin/bash -c "cd /workspace && /bin/bash debug.sh"
    