name: Publish GitHub Page

on:
  push:
    branches:
      - master

jobs:
  Build and Publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build pages
        shell: bash
        run: docker-compose up

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./landingpage/build
          cname: www.kawauso-lab.org
